name: tnc-project-work
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - rasterio
  - scikit-learn
  - xgboost
  - lightgbm
  - joblib
